#ifndef __INCLUDE_OBJ_H__
#define __INCLUDE_OBJ_H__

#if !defined(__cplusplus)
#error C++ compiler required
#endif

#include <objbase.h>

class dmsoft
{
private:
    IDispatch* obj;

public:
    dmsoft();
    virtual ~dmsoft();

    virtual long SetRowGapNoDict(long row_gap);
    virtual long MoveDD(long dx, long dy);
    virtual long FreeScreenData(long handle);
    virtual CString GetWordsNoDict(long x1, long y1, long x2, long y2, const TCHAR* color);
    virtual long FindWindow(const TCHAR* class_name, const TCHAR* title_name);
    virtual long EnableRealKeypad(long en);
    virtual long MoveFile(const TCHAR* src_file, const TCHAR* dst_file);
    virtual long SetEnv(long index, const TCHAR* name, const TCHAR* value);
    virtual long FoobarTextLineGap(long hwnd, long gap);
    virtual long SwitchBindWindow(long hwnd);
    virtual long GetLocale();
    virtual CString EnumIniSectionPwd(const TCHAR* file_name, const TCHAR* pwd);
    virtual long FindPic(long x1, long y1, long x2, long y2, const TCHAR* pic_name, const TCHAR* delta_color, double sim, long dir, long* x, long* y);
    virtual long FindInputMethod(const TCHAR* id);
    virtual CString FindStrE(long x1, long y1, long x2, long y2, const TCHAR* str, const TCHAR* color, double sim);
    virtual long EnterCri();
    virtual long SetExitThread(long en);
    virtual CString ReadStringAddr(long hwnd, LONGLONG addr, long tpe, long length);
    virtual long LoadPicByte(long addr, long size, const TCHAR* name);
    virtual CString AppendPicAddr(const TCHAR* pic_info, long addr, long size);
    virtual CString GetColorBGR(long x, long y);
    virtual CString ReadString(long hwnd, const TCHAR* addr, long tpe, long length);
    virtual long WriteIni(const TCHAR* section, const TCHAR* key, const TCHAR* v, const TCHAR* file_name);
    virtual long GetOsType();
    virtual long RegExNoMac(const TCHAR* code, const TCHAR* Ver, const TCHAR* ip);
    virtual long IsFileExist(const TCHAR* file_name);
    virtual long KeyUpChar(const TCHAR* key_str);
    virtual long SetClientSize(long hwnd, long width, long height);
    virtual long SetWindowSize(long hwnd, long width, long height);
    virtual long FoobarStopGif(long hwnd, long x, long y, const TCHAR* pic_name);
    virtual long RightClick();
    virtual long CreateFoobarRoundRect(long hwnd, long x, long y, long w, long h, long rw, long rh);
    virtual CString OcrInFile(long x1, long y1, long x2, long y2, const TCHAR* pic_name, const TCHAR* color, double sim);
    virtual CString GetAveHSV(long x1, long y1, long x2, long y2);
    virtual CString FaqSend(const TCHAR* server, long handle, long request_type, long time_out);
    virtual long FoobarSetSave(long hwnd, const TCHAR* file_name, long en, const TCHAR* header);
    virtual CString FindColorEx(long x1, long y1, long x2, long y2, const TCHAR* color, double sim, long dir);
    virtual long ClientToScreen(long hwnd, long* x, long* y);
    virtual long SetShowErrorMsg(long show);
    virtual long SetDictPwd(const TCHAR* pwd);
    virtual long delay(long mis);
    virtual float ReadFloatAddr(long hwnd, LONGLONG addr);
    virtual long SetClipboard(const TCHAR* data);
    virtual long SetMouseSpeed(long speed);
    virtual long EnableKeypadMsg(long en);
    virtual CString FindStrWithFontE(long x1, long y1, long x2, long y2, const TCHAR* str, const TCHAR* color, double sim, const TCHAR* font_name, long font_size, long flag);
    virtual long DeleteIniPwd(const TCHAR* section, const TCHAR* key, const TCHAR* file_name, const TCHAR* pwd);
    virtual CString FindPicE(long x1, long y1, long x2, long y2, const TCHAR* pic_name, const TCHAR* delta_color, double sim, long dir);
    virtual CString GetAveRGB(long x1, long y1, long x2, long y2);
    virtual long UseDict(long index);
    virtual CString GetCursorShapeEx(long tpe);
    virtual CString RGB2BGR(const TCHAR* rgb_color);
    virtual CString GetColor(long x, long y);
    virtual long SendStringIme(const TCHAR* str);
    virtual CString MoveToEx(long x, long y, long w, long h);
    virtual CString GetWindowClass(long hwnd);
    virtual long ReleaseRef();
    virtual long ShowScrMsg(long x1, long y1, long x2, long y2, const TCHAR* msg, const TCHAR* color);
    virtual CString FaqFetch();
    virtual long Log(const TCHAR* info);
    virtual long SetWordLineHeightNoDict(long line_height);
    virtual long FoobarDrawText(long hwnd, long x, long y, long w, long h, const TCHAR* text, const TCHAR* color, long align);
    virtual CString GetPath();
    virtual long DmGuard(long en, const TCHAR* tpe);
    virtual CString EnumWindowByProcessId(long pid, const TCHAR* title, const TCHAR* class_name, long filter);
    virtual CString BGR2RGB(const TCHAR* bgr_color);
    virtual long CopyFile(const TCHAR* src_file, const TCHAR* dst_file, long over);
    virtual long SetUAC(long uac);
    virtual long CaptureGif(long x1, long y1, long x2, long y2, const TCHAR* file_name, long delay, long time);
    virtual CString GetColorHSV(long x, long y);
    virtual long SendString(long hwnd, const TCHAR* str);
    virtual long CreateFoobarEllipse(long hwnd, long x, long y, long w, long h);
    virtual CString FindStrExS(long x1, long y1, long x2, long y2, const TCHAR* str, const TCHAR* color, double sim);
    virtual long SetColGapNoDict(long col_gap);
    virtual long DisableScreenSave();
    virtual long FindStrWithFont(long x1, long y1, long x2, long y2, const TCHAR* str, const TCHAR* color, double sim, const TCHAR* font_name, long font_size, long flag, long* x, long* y);
    virtual long GetColorNum(long x1, long y1, long x2, long y2, const TCHAR* color, double sim);
    virtual long GetFileLength(const TCHAR* file_name);
    virtual long EncodeFile(const TCHAR* file_name, const TCHAR* pwd);
    virtual CString FindMultiColorE(long x1, long y1, long x2, long y2, const TCHAR* first_color, const TCHAR* offset_color, double sim, long dir);
    virtual long EnableMouseAccuracy(long en);
    virtual long KeyPressStr(const TCHAR* key_str, long delay);
    virtual CString IntToData(LONGLONG int_value, long tpe);
    virtual CString ReadIniPwd(const TCHAR* section, const TCHAR* key, const TCHAR* file_name, const TCHAR* pwd);
    virtual long FaqIsPosted();
    virtual long Stop(long id);
    virtual long WheelDown();
    virtual long FoobarSetFont(long hwnd, const TCHAR* font_name, long size, long flag);
    virtual CString ReadDataAddr(long hwnd, LONGLONG addr, long length);
    virtual LONGLONG ReadIntAddr(long hwnd, LONGLONG addr, long tpe);
    virtual long GetWordResultPos(const TCHAR* str, long index, long* x, long* y);
    virtual long DownloadFile(const TCHAR* url, const TCHAR* save_file, long timeout);
    virtual long SetMinColGap(long col_gap);
    virtual long InitCri();
    virtual long WriteIniPwd(const TCHAR* section, const TCHAR* key, const TCHAR* v, const TCHAR* file_name, const TCHAR* pwd);
    virtual long CheckUAC();
    virtual long LockInput(long locks);
    virtual long LeftUp();
    virtual CString GetRealPath(const TCHAR* path);
    virtual CString GetPicSize(const TCHAR* pic_name);
    virtual CString SortPosDistance(const TCHAR* all_pos, long tpe, long x, long y);
    virtual long Int64ToInt32(LONGLONG v);
    virtual long AsmSetTimeout(long time_out, long param);
    virtual long EnableRealMouse(long en, long mousedelay, long mousestep);
    virtual double ReadDoubleAddr(long hwnd, LONGLONG addr);
    virtual long EnableKeypadSync(long en, long time_out);
    virtual CString EnumIniKey(const TCHAR* section, const TCHAR* file_name);
    virtual long SetWordLineHeight(long line_height);
    virtual long EnableGetColorByCapture(long en);
    virtual CString GetWordResultStr(const TCHAR* str, long index);
    virtual long FreeProcessMemory(long hwnd);
    virtual long WriteDouble(long hwnd, const TCHAR* addr, double v);
    virtual long CreateFoobarRect(long hwnd, long x, long y, long w, long h);
    virtual long GetTime();
    virtual CString FindNearestPos(const TCHAR* all_pos, long tpe, long x, long y);
    virtual long KeyUp(long vk);
    virtual long GetResultPos(const TCHAR* str, long index, long* x, long* y);
    virtual long SetDisplayDelay(long t);
    virtual CString FindIntEx(long hwnd, const TCHAR* addr_range, LONGLONG int_value_min, LONGLONG int_value_max, long tpe, long steps, long multi_thread, long mode);
    virtual long EnableDisplayDebug(long enable_debug);
    virtual long FoobarClearText(long hwnd);
    virtual long LeftClick();
    virtual long ReadDataToBin(long hwnd, const TCHAR* addr, long length);
    virtual long LeaveCri();
    virtual CString GetCursorShape();
    virtual CString SelectFile();
    virtual long SetLocale();
    virtual long LockDisplay(long locks);
    virtual CString FindString(long hwnd, const TCHAR* addr_range, const TCHAR* string_value, long tpe);
    virtual CString EnumProcess(const TCHAR* name);
    virtual long GetCursorPos(long* x, long* y);
    virtual CString GetDir(long tpe);
    virtual long CreateFoobarCustom(long hwnd, long x, long y, const TCHAR* pic, const TCHAR* trans_color, double sim);
    virtual CString GetDisplayInfo();
    virtual long GetWindowState(long hwnd, long flag);
    virtual long FoobarTextPrintDir(long hwnd, long dir);
    virtual CString GetNetTime();
    virtual long SetScreen(long width, long height, long depth);
    virtual long EnablePicCache(long en);
    virtual LONGLONG VirtualAllocEx(long hwnd, LONGLONG addr, long size, long tpe);
    virtual CString FindData(long hwnd, const TCHAR* addr_range, const TCHAR* data);
    virtual long IsFolderExist(const TCHAR* folder);
    virtual long FindStr(long x1, long y1, long x2, long y2, const TCHAR* str, const TCHAR* color, double sim, long* x, long* y);
    virtual CString FloatToData(float float_value);
    virtual CString FindInt(long hwnd, const TCHAR* addr_range, LONGLONG int_value_min, LONGLONG int_value_max, long tpe);
    virtual long UnBindWindow();
    virtual long WriteDataFromBin(long hwnd, const TCHAR* addr, long data, long length);
    virtual CString GetNetTimeByIp(const TCHAR* ip);
    virtual CString FindDouble(long hwnd, const TCHAR* addr_range, double double_value_min, double double_value_max);
    virtual long GetNowDict();
    virtual long RunApp(const TCHAR* path, long mode);
    virtual long GetLastError();
    virtual CString FindStringEx(long hwnd, const TCHAR* addr_range, const TCHAR* string_value, long tpe, long steps, long multi_thread, long mode);
    virtual long CheckFontSmooth();
    virtual CString VirtualQueryEx(long hwnd, LONGLONG addr, long pmbi);
    virtual long CmpColor(long x, long y, const TCHAR* color, double sim);
    virtual CString ReadFileData(const TCHAR* file_name, long start_pos, long end_pos);
    virtual long GetClientRect(long hwnd, long* x1, long* y1, long* x2, long* y2);
    virtual long FoobarTextRect(long hwnd, long x, long y, long w, long h);
    virtual long GetClientSize(long hwnd, long* width, long* height);
    virtual long MiddleClick();
    virtual long FindWindowByProcessId(long process_id, const TCHAR* class_name, const TCHAR* title_name);
    virtual long GetForegroundWindow();
    virtual long EnableFakeActive(long en);
    virtual CString EnumWindowByProcess(const TCHAR* process_name, const TCHAR* title, const TCHAR* class_name, long filter);
    virtual long SetDictMem(long index, long addr, long size);
    virtual long MoveWindow(long hwnd, long x, long y);
    virtual long GetFps();
    virtual long FindColor(long x1, long y1, long x2, long y2, const TCHAR* color, double sim, long dir, long* x, long* y);
    virtual long FaqGetSize(long handle);
    virtual long GetScreenHeight();
    virtual long FindWindowSuper(const TCHAR* spec1, long flag1, long type1, const TCHAR* spec2, long flag2, long type2);
    virtual CString FindStrEx(long x1, long y1, long x2, long y2, const TCHAR* str, const TCHAR* color, double sim);
    virtual long SetWindowTransparent(long hwnd, long v);
    virtual long SetWordGap(long word_gap);
    virtual long EnableBind(long en);
    virtual long IsBind(long hwnd);
    virtual long MiddleUp();
    virtual long FaqCaptureString(const TCHAR* str);
    virtual long GetDPI();
    virtual long RightUp();
    virtual long CaptureJpg(long x1, long y1, long x2, long y2, const TCHAR* file_name, long quality);
    virtual double ReadDouble(long hwnd, const TCHAR* addr);
    virtual long ForceUnBindWindow(long hwnd);
    virtual CString Ocr(long x1, long y1, long x2, long y2, const TCHAR* color, double sim);
    virtual LONGLONG GetRemoteApiAddress(long hwnd, LONGLONG base_addr, const TCHAR* fun_name);
    virtual long RegEx(const TCHAR* code, const TCHAR* Ver, const TCHAR* ip);
    virtual long FindStrFast(long x1, long y1, long x2, long y2, const TCHAR* str, const TCHAR* color, double sim, long* x, long* y);
    virtual long Delays(long min_s, long max_s);
    virtual LONGLONG AsmCall(long hwnd, long mode);
    virtual long GetWindowProcessId(long hwnd);
    virtual long GetForegroundFocus();
    virtual CString FindPicEx(long x1, long y1, long x2, long y2, const TCHAR* pic_name, const TCHAR* delta_color, double sim, long dir);
    virtual long UnLoadDriver();
    virtual long EnableShareDict(long en);
    virtual long AsmAdd(const TCHAR* asm_ins);
    virtual long GetResultCount(const TCHAR* str);
    virtual long SetExcludeRegion(long tpe, const TCHAR* info);
    virtual CString FindFloatEx(long hwnd, const TCHAR* addr_range, float float_value_min, float float_value_max, long steps, long multi_thread, long mode);
    virtual long FindMultiColor(long x1, long y1, long x2, long y2, const TCHAR* first_color, const TCHAR* offset_color, double sim, long dir, long* x, long* y);
    virtual CString ReadIni(const TCHAR* section, const TCHAR* key, const TCHAR* file_name);
    virtual CString FindColorBlockEx(long x1, long y1, long x2, long y2, const TCHAR* color, double sim, long count, long width, long height);
    virtual CString FindPicS(long x1, long y1, long x2, long y2, const TCHAR* pic_name, const TCHAR* delta_color, double sim, long dir, long* x, long* y);
    virtual CString FindColorE(long x1, long y1, long x2, long y2, const TCHAR* color, double sim, long dir);
    virtual long KeyPressChar(const TCHAR* key_str);
    virtual long ScreenToClient(long hwnd, long* x, long* y);
    virtual long GetBindWindow();
    virtual long KeyDownChar(const TCHAR* key_str);
    virtual CString OcrExOne(long x1, long y1, long x2, long y2, const TCHAR* color, double sim);
    virtual long FaqCaptureFromFile(long x1, long y1, long x2, long y2, const TCHAR* file_name, long quality);
    virtual long FoobarClose(long hwnd);
    virtual long FoobarStartGif(long hwnd, long x, long y, const TCHAR* pic_name, long repeat_limit, long delay);
    virtual CString GetWindowProcessPath(long hwnd);
    virtual long FoobarPrintText(long hwnd, const TCHAR* text, const TCHAR* color);
    virtual long GetScreenData(long x1, long y1, long x2, long y2);
    virtual long DeleteIni(const TCHAR* section, const TCHAR* key, const TCHAR* file_name);
    virtual long FoobarDrawPic(long hwnd, long x, long y, const TCHAR* pic, const TCHAR* trans_color);
    virtual long RightDown();
    virtual CString SelectDirectory();
    virtual long FoobarSetTrans(long hwnd, long trans, const TCHAR* color, double sim);
    virtual long SaveDict(long index, const TCHAR* file_name);
    virtual long WriteFloat(long hwnd, const TCHAR* addr, float v);
    virtual long FaqPost(const TCHAR* server, long handle, long request_type, long time_out);
    virtual long DelEnv(long index, const TCHAR* name);
    virtual CString OcrEx(long x1, long y1, long x2, long y2, const TCHAR* color, double sim);
    virtual long EnableFontSmooth();
    virtual long SetMinRowGap(long row_gap);
    virtual long GetWindow(long hwnd, long flag);
    virtual CString GetClipboard();
    virtual long GetID();
    virtual long BindWindowEx(long hwnd, const TCHAR* display, const TCHAR* mouse, const TCHAR* keypad, const TCHAR* public_desc, long mode);
    virtual long VirtualProtectEx(long hwnd, LONGLONG addr, long size, long tpe, long old_protect);
    virtual CString FetchWord(long x1, long y1, long x2, long y2, const TCHAR* color, const TCHAR* word);
    virtual long FindMulColor(long x1, long y1, long x2, long y2, const TCHAR* color, double sim);
    virtual long AddDict(long index, const TCHAR* dict_info);
    virtual long SpeedNormalGraphic(long en);
    virtual CString GetEnv(long index, const TCHAR* name);
    virtual long FindWindowEx(long parent, const TCHAR* class_name, const TCHAR* title_name);
    virtual long CheckInputMethod(long hwnd, const TCHAR* id);
    virtual long SetDisplayInput(const TCHAR* mode);
    virtual long GetKeyState(long vk);
    virtual long SetWindowText(long hwnd, const TCHAR* text);
    virtual CString MatchPicName(const TCHAR* pic_name);
    virtual long KeyPress(long vk);
    virtual long Reg(const TCHAR* code, const TCHAR* Ver);
    virtual long GetSpecialWindow(long flag);
    virtual long IsDisplayDead(long x1, long y1, long x2, long y2, long t);
    virtual long WriteFloatAddr(long hwnd, LONGLONG addr, float v);
    virtual CString GetBasePath();
    virtual long FindWindowByProcess(const TCHAR* process_name, const TCHAR* class_name, const TCHAR* title_name);
    virtual long GetPointWindow(long x, long y);
    virtual CString DoubleToData(double double_value);
    virtual long GetScreenDepth();
    virtual CString FindMultiColorEx(long x1, long y1, long x2, long y2, const TCHAR* first_color, const TCHAR* offset_color, double sim, long dir);
    virtual long WriteData(long hwnd, const TCHAR* addr, const TCHAR* data);
    virtual CString ReadData(long hwnd, const TCHAR* addr, long length);
    virtual long WriteDoubleAddr(long hwnd, LONGLONG addr, double v);
    virtual long LoadPic(const TCHAR* pic_name);
    virtual long FindColorBlock(long x1, long y1, long x2, long y2, const TCHAR* color, double sim, long count, long width, long height, long* x, long* y);
    virtual long EnableMouseMsg(long en);
    virtual long AsmClear();
    virtual long WaitKey(long key_code, long time_out);
    virtual long CapturePng(long x1, long y1, long x2, long y2, const TCHAR* file_name);
    virtual long GetOsBuildNumber();
    virtual long SetParam64ToPointer();
    virtual long SetDisplayRefreshDelay(long t);
    virtual long MiddleDown();
    virtual long FreePic(const TCHAR* pic_name);
    virtual long SetEnumWindowDelay(long delay);
    virtual CString GetDiskSerial();
    virtual long FoobarUpdate(long hwnd);
    virtual CString GetMac();
    virtual CString FindStrFastE(long x1, long y1, long x2, long y2, const TCHAR* str, const TCHAR* color, double sim);
    virtual long WriteDataAddrFromBin(long hwnd, LONGLONG addr, long data, long length);
    virtual long SetPath(const TCHAR* path);
    virtual long EnableMouseSync(long en, long time_out);
    virtual CString GetDictInfo(const TCHAR* str, const TCHAR* font_name, long font_size, long flag);
    virtual long VirtualFreeEx(long hwnd, LONGLONG addr);
    virtual long SetDict(long index, const TCHAR* dict_name);
    virtual CString ReadFile(const TCHAR* file_name);
    virtual long DisableFontSmooth();
    virtual long SetExactOcr(long exact_ocr);
    virtual CString GetCommandLine(long hwnd);
    virtual CString EnumWindowSuper(const TCHAR* spec1, long flag1, long type1, const TCHAR* spec2, long flag2, long type2, long sort);
    virtual LONGLONG ReadInt(long hwnd, const TCHAR* addr, long tpe);
    virtual CString ExcludePos(const TCHAR* all_pos, long tpe, long x1, long y1, long x2, long y2);
    virtual long Play(const TCHAR* file_name);
    virtual long RegNoMac(const TCHAR* code, const TCHAR* Ver);
    virtual long WriteFile(const TCHAR* file_name, const TCHAR* content);
    virtual long WriteIntAddr(long hwnd, LONGLONG addr, long tpe, LONGLONG v);
    virtual CString FindDataEx(long hwnd, const TCHAR* addr_range, const TCHAR* data, long steps, long multi_thread, long mode);
    virtual CString GetWindowTitle(long hwnd);
    virtual long FoobarLock(long hwnd);
    virtual CString ExecuteCmd(const TCHAR* cmd, const TCHAR* current_dir, long time_out);
    virtual long GetScreenWidth();
    virtual CString EnumIniSection(const TCHAR* file_name);
    virtual long ImageToBmp(const TCHAR* pic_name, const TCHAR* bmp_name);
    virtual CString FindPicExS(long x1, long y1, long x2, long y2, const TCHAR* pic_name, const TCHAR* delta_color, double sim, long dir);
    virtual CString FindShapeE(long x1, long y1, long x2, long y2, const TCHAR* offset_color, double sim, long dir);
    virtual CString GetDict(long index, long font_index);
    virtual long GetMousePointWindow();
    virtual LONGLONG GetModuleBaseAddr(long hwnd, const TCHAR* module_name);
    virtual CString DisAssemble(const TCHAR* asm_code, LONGLONG base_addr, long is_64bit);
    virtual long DownCpu(long rate);
    virtual long GetDictCount(long index);
    virtual long SetPicPwd(const TCHAR* pwd);
    virtual long DisableCloseDisplayAndSleep();
    virtual long GetScreenDataBmp(long x1, long y1, long x2, long y2, long* data, long* size);
    virtual long GetDmCount();
    virtual long SetMemoryHwndAsProcessId(long en);
    virtual CString FindShapeEx(long x1, long y1, long x2, long y2, const TCHAR* offset_color, double sim, long dir);
    virtual LONGLONG AsmCallEx(long hwnd, long mode, const TCHAR* base_addr);
    virtual CString GetMachineCode();
    virtual long FindPicMem(long x1, long y1, long x2, long y2, const TCHAR* pic_info, const TCHAR* delta_color, double sim, long dir, long* x, long* y);
    virtual long SendStringIme2(long hwnd, const TCHAR* str, long mode);
    virtual long WriteString(long hwnd, const TCHAR* addr, long tpe, const TCHAR* v);
    virtual long FoobarFillRect(long hwnd, long x1, long y1, long x2, long y2, const TCHAR* color);
    virtual long FindShape(long x1, long y1, long x2, long y2, const TCHAR* offset_color, double sim, long dir, long* x, long* y);
    virtual long SetDisplayAcceler(long level);
    virtual CString FindStrFastS(long x1, long y1, long x2, long y2, const TCHAR* str, const TCHAR* color, double sim, long* x, long* y);
    virtual long GetWindowRect(long hwnd, long* x1, long* y1, long* x2, long* y2);
    virtual long FoobarDrawLine(long hwnd, long x1, long y1, long x2, long y2, const TCHAR* color, long style, long width);
    virtual long EnableSpeedDx(long en);
    virtual CString GetMachineCodeNoMac();
    virtual CString GetProcessInfo(long pid);
    virtual long SetWindowState(long hwnd, long flag);
    virtual long GetCpuType();
    virtual long LeftDown();
    virtual long HackSpeed(double rate);
    virtual long DisablePowerSave();
    virtual long ReadDataAddrToBin(long hwnd, LONGLONG addr, long length);
    virtual long OpenProcess(long pid);
    virtual CString FindPicMemE(long x1, long y1, long x2, long y2, const TCHAR* pic_info, const TCHAR* delta_color, double sim, long dir);
    virtual CString GetWords(long x1, long y1, long x2, long y2, const TCHAR* color, double sim);
    virtual float ReadFloat(long hwnd, const TCHAR* addr);
    virtual long SetMouseDelay(const TCHAR* tpe, long delay);
    virtual long FaqCapture(long x1, long y1, long x2, long y2, long quality, long delay, long time);
    virtual long DeleteFolder(const TCHAR* folder_name);
    virtual long SetWordGapNoDict(long word_gap);
    virtual long BindWindow(long hwnd, const TCHAR* display, const TCHAR* mouse, const TCHAR* keypad, long mode);
    virtual long SetAero(long en);
    virtual CString FindPicMemEx(long x1, long y1, long x2, long y2, const TCHAR* pic_info, const TCHAR* delta_color, double sim, long dir);
    virtual long FaqCancel();
    virtual long Beep(long fre, long delay);
    virtual CString Ver();
    virtual long GetMouseSpeed();
    virtual long DeleteFile(const TCHAR* file_name);
    virtual CString GetCursorSpot();
    virtual long SendCommand(const TCHAR* cmd);
    virtual CString FindStrFastEx(long x1, long y1, long x2, long y2, const TCHAR* str, const TCHAR* color, double sim);
    virtual long WriteInt(long hwnd, const TCHAR* addr, long tpe, LONGLONG v);
    virtual long Capture(long x1, long y1, long x2, long y2, const TCHAR* file_name);
    virtual CString EnumWindow(long parent, const TCHAR* title, const TCHAR* class_name, long filter);
    virtual long Is64Bit();
    virtual long ClearDict(long index);
    virtual long StrStr(const TCHAR* s, const TCHAR* str);
    virtual long ActiveInputMethod(long hwnd, const TCHAR* id);
    virtual long SendPaste(long hwnd);
    virtual CString StringToData(const TCHAR* string_value, long tpe);
    virtual long CapturePre(const TCHAR* file_name);
    virtual long ShowTaskBarIcon(long hwnd, long is_show);
    virtual CString FindStrFastExS(long x1, long y1, long x2, long y2, const TCHAR* str, const TCHAR* color, double sim);
    virtual long SetExportDict(long index, const TCHAR* dict_name);
    virtual long WriteDataAddr(long hwnd, LONGLONG addr, const TCHAR* data);
    virtual long GetWordResultCount(const TCHAR* str);
    virtual long FaqRelease(long handle);
    virtual long SetKeypadDelay(const TCHAR* tpe, long delay);
    virtual long EnableKeypadPatch(long en);
    virtual long TerminateProcess(long pid);
    virtual CString FindDoubleEx(long hwnd, const TCHAR* addr_range, double double_value_min, double double_value_max, long steps, long multi_thread, long mode);
    virtual long CreateFolder(const TCHAR* folder_name);
    virtual long WheelUp();
    virtual CString FindFloat(long hwnd, const TCHAR* addr_range, float float_value_min, float float_value_max);
    virtual long LockMouseRect(long x1, long y1, long x2, long y2);
    virtual CString GetNetTimeSafe();
    virtual long KeyDown(long vk);
    virtual CString FindStrS(long x1, long y1, long x2, long y2, const TCHAR* str, const TCHAR* color, double sim, long* x, long* y);
    virtual long MoveR(long rx, long ry);
    virtual long WriteStringAddr(long hwnd, LONGLONG addr, long tpe, const TCHAR* v);
    virtual CString Md5(const TCHAR* str);
    virtual long DecodeFile(const TCHAR* file_name, const TCHAR* pwd);
    virtual long SendString2(long hwnd, const TCHAR* str);
    virtual long EnableIme(long en);
    virtual long FoobarUnlock(long hwnd);
    virtual CString Assemble(LONGLONG base_addr, long is_64bit);
    virtual CString EnumIniKeyPwd(const TCHAR* section, const TCHAR* file_name, const TCHAR* pwd);
    virtual long SetSimMode(long mode);
    virtual long SetMemoryFindResultToFile(const TCHAR* file_name);
    virtual long ExitOs(long tpe);
    virtual long LeftDoubleClick();
    virtual long MoveTo(long x, long y);
    virtual CString FindStrWithFontEx(long x1, long y1, long x2, long y2, const TCHAR* str, const TCHAR* color, double sim, const TCHAR* font_name, long font_size, long flag);
};

#endif
