[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=866ea68e-7db5-4154-b4cd-caa191a68869
Description=^ด๚ธี
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]

	TracePrint ( 1^ 2)
	TracePrint ( 2^ 2)
	TracePrint ( 4^ 2)
	TracePrint ( 8^ 2)
	TracePrint ( 10^ 2)
	TracePrint ( 12^ 2)
