[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=60607969-600d-440c-9ac0-f1dc2a13ca4c
Description=§Ö³t¬Iªk
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
Do
    KeyDown "F6", 1
    KeyUp "F6", 1
    Delay 10
    LeftClick 1
Loop